[tool.poetry]
name = "caikit-tgis-serving"
version = "0.0.1"
description = ""
authors = ["Daniele Trifirò <dtrifiro@redhat.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
caikit = "*"
caikit-nlp = {git = "https://github.com/caikit/caikit-nlp", rev = "0.3.3"}
caikit-tgis-backend = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
